      - name: Build geoip.dat
        run: |

          git clone \
            --depth 1 \
            --filter=blob:none \
            https://github.com/v2fly/geoip.git geoip-tool


          curl -fsSL \
            https://github.com/v2fly/geoip/releases/latest/download/geoip.dat \
            -o geoip-tool/upstream-geoip.dat


          cp build/russia-inside.txt \
            geoip-tool/russia-inside.txt || true


          cp config/geoip-custom.json \
            geoip-tool/config-custom.json


          cd geoip-tool


          echo "========== GEOIP CONFIG =========="
          cat config-custom.json
          echo "=================================="


          go run ./ -c config-custom.json


          echo "========== GEOIP RESULT =========="

          ls -lh output/geoip.dat


          SIZE=$(stat -c%s output/geoip.dat)

          echo "SIZE: $SIZE bytes"


          if [ "$SIZE" -gt 5000000 ]; then
            echo "ERROR: geoip.dat too large"
            exit 1
          fi


          cp output/geoip.dat ../release/geoip.dat
