name: Update geo files

on:
  schedule:
    - cron: "0 3 */3 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Trigger full build
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build.yml",
              ref: "main"
            })
