name: Update routing-template.json

on:
  workflow_dispatch:   # вручную
  schedule:
    - cron: '20 4 * * *'   # точно как в старом #76

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

       - name: Update routing-template.json из бэкапа
      run: |
        git checkout HEAD -- routing-template.json
        git add routing-template.json
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "Update routing-template.json"
        git push
